games/urls.py
from django.urls import path

from . import views

app_name = 'games'
urlpatterns = [
    # ex: /polls/
    # path('', views.index, name='index'),
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),

    path('', views.index, name='index'),
    path('<int:game_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('result/', views.result, name='result'),
]

participations/urls.py
from django.urls import path

from . import views

app_name = 'participations'
urlpatterns = [

    path('', views.index, name='index'),
    path('<int:game_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('result/', views.result, name='result'),
]

tournament/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('game/', include('games.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', TemplateView.as_view(template_name='base.html'), name='home'),
]

accounts/models.py
from django.db import models

# Create your models here.

games/models.py
from django.db import models
from django.utils import timezone

class Game(models.Model):
    owner_user_code = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    game_name = models.CharField(max_length=50, null=True)
    num_people = models.IntegerField(default=0)
    reception_start_time = models.DateTimeField(default=timezone.now)
    reception_end_time = models.DateTimeField(default=timezone.now)
    game_start_time = models.DateTimeField(default=timezone.now)
    game_end_time = models.DateTimeField(default=timezone.now)
    outline = models.CharField(max_length=50, null=True)
    status = models.IntegerField(default=0)

    def __str__(self):
        return self.name

participations/models.py
from django.db import models
from django.utils import timezone

from django.contrib.auth.models import User
from games.models import Game


class Participations(models.Model):
    Game = models.ForeignKey(Game, on_delete=models.SET_NULL, null=True)
    User = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    redist_time = models.DateTimeField(default=timezone.now)
    is_check_in = models.BooleanField(default=False)

    def __str__(self):
        return self.user_name

accounts/views.py
from django.shortcuts import render

# Create your views here.

games/views.py
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

from .models import Game


# Create your views here.
def index(request):
    game_list = Game.objects.order_by('id')[:5]
    template = loader.get_template('games/index.html')
    context = {
        'game_list': game_list,
    }
    return HttpResponse(template.render(context, request))

def create(request):
    template = loader.get_template('games/create.html')

    return render(request, 'games/create.html')


def detail(request, game_id):
    try:
        game = Game.objects.get(pk=game_id)
    except Game.DoesNotExist:
        raise Http404("Game does not exist")
    return render(request, 'games/detail.html', {'game': game})


def result(request):
    game = Game(
        name=request.POST['name'],
        num_people=request.POST['num_people'],
        outline=request.POST['outline'],
        reception_start_time=request.POST['reception_start_time'],
        reception_end_time=request.POST['reception_end_time'],
        game_start_time=request.POST['game_start_time'],
        game_end_time=request.POST['game_end_time'],
        game_name=request.POST['game_name'],
        owner_user_code="hogehoge"

    )

    game.save()

    game_list = Game.objects.order_by('id')[:5]
    template = loader.get_template('games/index.html')
    context = {
        'game_list': game_list,
    }
    return HttpResponse(template.render(context, request))

participations/views.py
from django.shortcuts import render
from games.models import Game

# Create your views here.

def lottery(id):
    max_participations = Game.objects.num_people.get(id=id)

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>トーナメント</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'games/style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_blue.css">

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.css" rel="stylesheet">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <style>
        body{
            margin: 0 auto;
        }
    </style>
</head>
<body>


<header>
    <div class="logo">
        <a href="{% url 'games:index' %}">
            <img src="{% static 'games/logo.png' %}">
        </a>
    </div>

    <nav>
        <ul>
            <li><a href="{% url 'games:index' %}">マイページ</a></li>
        </ul>
    </nav>
</header>

<div class="container">

    <div class="side_ber">
        <ul>
            <li><a href="{% url 'games:create' %}">大会を開催する</a></li>
            <li><a href="#">大会に参加する</a></li>
            <li><a href="#">過去の大会を見る</a></li>
        </ul>
    </div>

    <div class="main">

    {% block content %}
    {% endblock %}

    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>
<script>
    flatpickr.localize(flatpickr.l10ns.ja);
    flatpickr('.input_calendar');
</script>
<script>
    flatpickr.localize(flatpickr.l10ns.ja);
    flatpickr('.input_calendar', {
        enableTime: true
    });
</script>

<script>
    $(function() {
        var $textarea = $('#textarea');
        var lineHeight = parseInt($textarea.css('lineHeight'));
        $textarea.on('input', function(evt) {
            var lines = ($(this).val() + '\n').match(/\n/g).length;
            $(this).height(lineHeight * lines);
        });
    });
</script>

</body>
</html>

templates/games/create.html
{% extends 'base/base.html' %}

{% block content %}

    <h2>大会を開催する</h2>


    <form action="{% url 'games:result' %}" method="post" class="create_game">
        {% csrf_token %}

        <div class="input_component">
            <input class="under_line" type="text" name="name" placeholder=" " required>
            <label>大会名</label>
            <span class="focus_line"></span>
        </div>

        <div class="input_component">
            <select class="under_line" name="num_people" required>
                <option value="4">4</option>
                <option value="8">8</option>
                <option value="16">16</option>
            </select>
            <p>参加人数</p>
            <span class="focus_line"></span>
        </div>

        <div class="input_component">
            <input class="under_line" type="text" name="game_name" placeholder=" " required>
            <label>ゲーム</label>
            <span class="focus_line"></span>
        </div>


        <div class="input_component">
            <textarea class="under_line" id="textarea" name="outline" placeholder=" " required></textarea>
            <label>説明</label>
            <span class="focus_line"></span>
        </div>

        <h3>期間設定</h3>

        <div class="time">
            <div class="time_component">
                <div class="input_component">
                <input type="text" class="input_calendar under_line" name="reception_start_time" placeholder="2020-01-05 12:00" required>
                <p>受付開始期間</p>
                <span class="focus_line"></span>
                </div>
            </div>

            <div class="period">
                <p>~</p>
            </div>

            <div class="time_component">
                <div class="input_component">
                <input type="text" class="input_calendar under_line" name="reception_end_time" placeholder="2020-01-05 12:00" required>
                <p>受付締切期間</p>
                <span class="focus_line"></span>
                </div>
            </div>
        </div>



        <div class="time">
            <div class="time_component">
                <div class="input_component">
                <input type="text"  class="input_calendar under_line" name="game_start_time" placeholder="2020-01-05 12:00" required>
                <p>大会開始時間</p>
                <span class="focus_line"></span>
                </div>
            </div>

            <div class="period">
                <p>~</p>
            </div>

            <div class="time_component">
                <div class="input_component">
                <input type="text"  class="input_calendar under_line" name="game_end_time" placeholder="2020-01-05 12:00" required>
                <p>予定終了時刻</p>
                <span class="focus_line"></span>
                </div>
            </div>
        </div>

        <input type="submit" class="regist_btn" value="作成する"></li>
    </form>


{% endblock %}

templates/games/detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>{{ game.name }}</h2>

    <div class="main_detail">
    <ul>
        <li>名前：{{ game.name }}</li>
        <li>人数：{{ game.num_people }}</li>
        <li>説明：{{ game.outline }}</li>
    </ul>
    </div>

    <div class="participant_list">
        <form action="{% url 'participations:create' %}" method="post" class="create_game">
            {% csrf_token %}
            <button class="regist_btn" >送信</button></form></div>
{% endblock %}

templates/games/index.html
{% extends 'base/base.html' %}

{% block content %}

<h2>参加中の大会一覧</h2>

{% if game_list %}
    {% for game in game_list %}
        <div class = "game_list">
            <a href="{% url 'games:detail' game.id %}">
                <div class="list_hedder">
                    <p>{{ game.name }}</p>
                </div>
                <div class="list_img">
                    <img src="http://placehold.jp/300x200.png">
                </div>

                <div class="list_body">
                    <p>開催日時：{{ game.game_start_time|date:"Y-n-j H:i" }}</p>
                    <p>ゲーム　：{{ game.game_name }}</p>
                </div>
            </a>
        </div>

    {% endfor %}

{% else %}
    <p>参加中の大会はありません。</p>
{% endif %}



{% endblock %}